apiVersion: v1
kind: Service
metadata:
  name: cdc-dashboard
  labels:
    app: cdc-dashboard
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: cdc-dashboard
  type: ClusterIP

